# Generated by Django 4.2.7 on 2025-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='moviei/images/default.jpg', upload_to='moviei/images/'),
        ),
    ]
