# Generated by Django 4.2.7 on 2025-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='media/moviei/images/default.jpg', upload_to='moviei/images/'),
        ),
    ]
